// 중요: @@SOCKET 으로 시작하는 항목은 executor를 타게 된다 .
export const socket = Object.freeze({
    SOCKET_CONNECT: '@@SOCKET/CONNECT',
    SOCKET_RECONNECT: '@@SOCKET/RECONNECT',
    SOCKET_DISCONNECT: '@@SOCKET/DISCONNECT',
    SOCKET_DISCONNECTED: 'SOCKET/DISCONNECTED',
    SOCKET_ON: 'message',
    SOCKET_ON_CHECKED: 'SOCKET/ON_CHECKED',
    SOCKET_TALK_CHECKED: 'SOCKET/TALK_CHECKED',
    SOCKET_EMIT: '@@SOCKET/EMIT',
    SOCKET_EMIT_TALK: '@@SOCKET/EMIT_TALK',

    SOCKET_TALK_INIT: 'SOCKET/SOCKET_TALK_INIT',

    RTC_INIT: 'SOCKET/RTC_INIT',
    RTC_LOCAL_STREAM: 'SOCKET/RTC_LOCAL_STREAM',
    RTC_LOCAL_RESOURCE_CHANGE: 'SOCKET/RTC_LOCAL_RESOURCE_CHANGE',

    RTC_REMOTE_APPEND: 'SOCKET/RTC_REMOTE_APPEND',
    RTC_REMOTE_REMOVE: 'SOCKET/RTC_REMOTE_REMOVE',

    RTC_CONNECT_STATUS: 'SOCKET/RTC_CONNECT_STATUS',
    RTC_CONNECT: '@@SOCKET/RTC_CONNECT',
    RTC_DISCONNECT: '@@SOCKET/RTC_DISCONNECT',

    RTC_VIDEO_CALL_STATUS: 'SOCKET/RTC_VIDEO_CALL_STATUS',
});

export default socket;
